apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:vWLK99OB,iv:7GGZTWaksiwPF6uu0hjm/NTACrSJgL8WAF49AYZE5Vo=,tag:sFwyqIqHS8Xn43f5a9/6GQ==,type:str]
    password: ENC[AES256_GCM,data:Wf8GztkuIiDspLa2LsLUVg==,iv:gGpPxQgUXKLEwiv7N9x8slQxIk54ql1IjZBioZHZywE=,tag:Cqc4O2uSz9kWHWa2uh795Q==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y0k5L2trRUZyVWwwTHIy
            YzdBYWtQWkZKZjVQbE5LTS9KaHZQdmlxd0ZRCk5QejJ4NFpBVFR2VkhleFBXcUh4
            Mi9UUkh1RDZGNHFsVE02QzFFN0FMdXcKLS0tIHBlVXhYYkszL3dFb3JacEIwYVlx
            dS80ODI3UHpEK3UwQi9Qa1phcXRXYmMKOafAJc6/wjLUTsvcECzg5aphiP2yHUfP
            VApkDkrQY+hSBxYE9TBYZRyKmfw53NyXJjIJZThexkeGjJExvDgI2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T20:21:31Z"
    mac: ENC[AES256_GCM,data:Tlk5GHzTlOHiZMsoaUtWLUwu7DZULcqLaqetAnedtOZol0T32wNJmQdtJP2VKD3M8imt8M2C28qESQwkOz6TnYmd7LQtXmr86DOP9Lb2l6Z1K77/DN5QXxGJva9RZeNF9h7gjQldUM/lmyBIxeFn1uOrHfwSEMrWIEKShQ8nYI8=,iv:VshT/2sKL0QNzyO3GzE6BbX5N2dvQGadFOZplu53Uio=,tag:3pVrnLBkpfr3mDkWoJSIag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
