---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace for SeaweedFS cluster workloads
  # Where master, filer, and volume pods will run
  - namespace.yaml

  # Seaweed custom resource
  # The operator will watch this and create StatefulSets, Services, etc.
  - seaweed.yaml
