---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # GitRepository pointing to tektoncd/operator repo at v0.77.0
  - repository.yaml
  # Flux Kustomization that applies the actual operator from the repo
  - operator-install.yaml
