---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Operator installation (GitRepository + HelmRelease)
  # Installs into tekton-operator namespace
  - repository.yaml
  - release.yaml
