---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # PVC + Deployment with LevelDB metadata storage
  # Single replica until we have distributed storage (Longhorn) or external DB (PostgreSQL)
  - deployment.yaml

  # ClusterIP service exposing S3 and HTTP APIs
  # Harbor will connect to: http://filer.seaweedfs.svc.cluster.local:8888
  - service.yaml
