---
# Kustomization for vendored Tekton Operator release manifest
# Downloaded from: https://storage.googleapis.com/tekton-releases/operator/previous/v0.77.0/release.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - release.yaml
