---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - metallb
  - external-dns
  - nvidia
  - pki
  - local-path-provisioner
  - local-path-usb-provisioner
  - kubevirt
  - prometheus-stack
  - prometheus-node-exporter
  - prometheus-blackbox-exporter
  - litmus
  - seaweedfs
  - tekton
  - docker-registry
  - loki
  - tempo
  - alloy
patches:
