---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - metallb
  - external-dns
  - nvidia
  - pki
  - local-path-provisioner
  - local-path-usb-provisioner
  - kubevirt
  - seaweedfs
  - tekton
  - docker-registry
patches:
