---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Tekton Operator (HelmRelease)
  # Installs the operator that manages Tekton custom resources
  # Creates tekton-operator namespace
  - operator/flux-kustomization.yaml
