apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - operator.yaml  # Layer 1: Operators deploy and create CRDs
  - cdi.yaml
  - instance.yaml  # Layer 2: KubeVirt CR (depends on operators)
