---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Tempo HelmRelease - distributed tracing backend
  - release.yaml
  # Grafana datasource - auto-discovered via label
  - datasource.yaml
