---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Operator installation (HelmRepository + HelmRelease)
  # Installs into seaweedfs-operator namespace
  - repository.yaml
  - operator.yaml
