apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # CDI operator from GitHub releases
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.63.1/cdi-operator.yaml
